### ISSUE TITLE
Using a Tile Stamp in an object layer does not automatically import the right tileset

### ISSUE THREAD

**Issue by tcoxon** [bjorn/tiled#1176]
If you use a Tile Stamp in a tile layer, the tileset that stamp uses is automatically referenced by the map.

This doesn't happen in object layers. If you use the Tile Object tool to place a Tile Stamp in an object layer, everything looks fine in the editor at first, but the tileset it uses isn't added to the tilesets view. If you save and reload the map, the tile data for that object is lost, and it becomes a generic rectangle object.

Tested with Tiled 0.15.

**Comment by bjorn** [comment]
Hmm, I'm trying to reproduce this but one thing I'm not managing to do is to get the 'Insert Tile' tool to insert a selected tile stamp. Making this possible was recently requested (#1147), but it's not currently possible in Tiled as far as I know. The only way to insert tiles would be to first select them in a tileset view, which implies the map already has the tileset added.

So please elaborate on the steps to reproduce this issue. I must be missing something!

**Comment by tcoxon** [comment]
I built Tiled from source, using the v0.15.0 tag, for Ubuntu 14.04 64bit. The only changes I've made to the source have been to [add a new tool linking against libtiled](https://github.com/tcoxon/tiled/commits/feature/formatconvert).

I've just reproduced it a few more times and recorded a video of my actions: https://youtu.be/0nBWYKwSb8g

I realized after recording that it wasn't the bug I thought it was. The tile I placed as an object was still selected in a tileset on the other map. So bug is actually that the insert tile tool lets you insert tiles that are available on _any map currently open_.

**Comment by bjorn** [comment]
Ah, good catch and thanks for the video! I don't think it will be hard to simply add the tileset when necessary.

**Comment by bjorn** [comment]
I must be missing something but I can't reproduce this issue. I've tried following exactly the steps in your video but the 'Insert Tile' tool does not let me insert a tile from another map. It shouldn't allow you to do that, because the current tile depends on what is selected in the tileset view, and nothing is selected there when there are no tilesets.

Since you are developing with Tiled as well, maybe you can help debug this problem by setting a breakpoint in `CreateObjectTool::setTile` to find out when the tile is being set for which its tileset isn't part of the map yet. I personally see it resetting it to 0x0 as it should and seem to be unable to get it to set a tile again if there aren't tilesets added to the map. Thanks!

**Comment by tcoxon** [comment]
Alright, I set a breakpoint on the `CreateObjectTool::setTile` function and captured the value of the `tile` parameter each time Tiled hit the breakpoint.

I had two tabs open in Tiled. The first had several tilesets loaded, and the second had one. In both tabs I had an object layer and the tile object tool selected.

In the first tab, I chose a tile in a tileset. When I clicked it, gdb printed:

```
Breakpoint 1, Tiled::Internal::CreateObjectTool::setTile (this=0xe95380, tile=0x4bea5c0) at createobjecttool.h:63
63	    void setTile(Tile *tile) { mTile = tile; }
```

When I switched to the second tab, it looks like the tile was reset to nil and then set to a non-nil value again:

```
Breakpoint 1, Tiled::Internal::CreateObjectTool::setTile (this=0xe95380, tile=0x0) at createobjecttool.h:63
63	    void setTile(Tile *tile) { mTile = tile; }

Breakpoint 1, Tiled::Internal::CreateObjectTool::setTile (this=0xe95380, tile=0x4bea5c0) at createobjecttool.h:63
63	    void setTile(Tile *tile) { mTile = tile; }
```

Then I clicked in the object layer of the second map, and the object was placed in the map without any tilesets getting imported.

Here's a backtrace from the second call to setTile when I switched to the second tab:

```
Breakpoint 1, Tiled::Internal::CreateObjectTool::setTile (this=0xe95380, tile=0x4c23960) at createobjecttool.h:63
63	    void setTile(Tile *tile) { mTile = tile; }
(gdb) bt
#0  Tiled::Internal::CreateObjectTool::setTile (this=0xe95380, tile=0x4c23960) at createobjecttool.h:63
#1  0x0000000000571c84 in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<Tiled::Tile*>, void, void (Tiled::Internal::CreateObjectTool::*)(Tiled::Tile*)>::call (f=
    (void (Tiled::Internal::CreateObjectTool::*)(Tiled::Internal::CreateObjectTool * const, Tiled::Tile *)) 0x56e012 <Tiled::Internal::CreateObjectTool::setTile(Tiled::Tile*)>, o=0xe95380, arg=0x7fffffffbab0) at /usr/include/qt5/QtCore/qobjectdefs_impl.h:508
#2  0x0000000000571734 in QtPrivate::FunctionPointer<void (Tiled::Internal::CreateObjectTool::*)(Tiled::Tile*)>::call<QtPrivate::List<Tiled::Tile*>, void> (f=
    (void (Tiled::Internal::CreateObjectTool::*)(Tiled::Internal::CreateObjectTool * const, Tiled::Tile *)) 0x56e012 <Tiled::Internal::CreateObjectTool::setTile(Tiled::Tile*)>, o=0xe95380, arg=0x7fffffffbab0) at /usr/include/qt5/QtCore/qobjectdefs_impl.h:527
#3  0x0000000000570cdb in QtPrivate::QSlotObject<void (Tiled::Internal::CreateObjectTool::*)(Tiled::Tile*), QtPrivate::List<Tiled::Tile*>, void>::impl (which=1, this_=0xe8cb70, r=0xe95380, a=0x7fffffffbab0, ret=0x0) at /usr/include/qt5/QtCore/qobject_impl.h:149
#4  0x00007ffff666dd73 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x000000000061ef11 in Tiled::Internal::TilesetDock::currentTileChanged (this=0xc64400, _t1=0x4c23960) at moc_tilesetdock.cpp:280
#6  0x00000000005e7f17 in Tiled::Internal::TilesetDock::setCurrentTile (this=0xc64400, tile=0x4c23960) at tilesetdock.cpp:788
#7  0x00000000005e6951 in Tiled::Internal::TilesetDock::currentTilesetChanged (this=0xc64400) at tilesetdock.cpp:496
#8  0x00000000005eef7e in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (Tiled::Internal::TilesetDock::*)()>::call(void (Tiled::Internal::TilesetDock::*)(), Tiled::Internal::TilesetDock*, void**) (
    f=(void (Tiled::Internal::TilesetDock::*)(Tiled::Internal::TilesetDock * const)) 0x5e68d4 <Tiled::Internal::TilesetDock::currentTilesetChanged()>, o=0xc64400, arg=0x7fffffffbd30) at /usr/include/qt5/QtCore/qobjectdefs_impl.h:508
#9  0x00000000005ee7aa in QtPrivate::FunctionPointer<void (Tiled::Internal::TilesetDock::*)()>::call<QtPrivate::List<>, void>(void (Tiled::Internal::TilesetDock::*)(), Tiled::Internal::TilesetDock*, void**) (
    f=(void (Tiled::Internal::TilesetDock::*)(Tiled::Internal::TilesetDock * const)) 0x5e68d4 <Tiled::Internal::TilesetDock::currentTilesetChanged()>, o=0xc64400, arg=0x7fffffffbd30) at /usr/include/qt5/QtCore/qobjectdefs_impl.h:527
#10 0x00000000005ed9dd in QtPrivate::QSlotObject<void (Tiled::Internal::TilesetDock::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0xcb5f00, r=0xc64400, a=0x7fffffffbd30, ret=0x0)
    at /usr/include/qt5/QtCore/qobject_impl.h:149
#11 0x00007ffff666dd73 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007ffff757eb3e in QStackedWidget::currentChanged(int) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007ffff757ec73 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007ffff666e2a6 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007ffff7578ae1 in QStackedLayout::currentChanged(int) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007ffff7230b53 in QStackedLayout::setCurrentIndex(int) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007ffff7231196 in QStackedLayout::takeAt(int) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007ffff722a477 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007ffff720cc5e in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007ffff7211e56 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007ffff6646c2d in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007ffff66750ae in QObjectPrivate::setParent_helper(QObject*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x00007ffff6675652 in QObject::~QObject() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#24 0x00007ffff7244c7a in QWidget::~QWidget() () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#25 0x000000000061fa6c in Tiled::Internal::TilesetView::~TilesetView (this=0x4d72d00, __in_chrg=<optimised out>) at tilesetview.h:37
#26 0x000000000061faa4 in Tiled::Internal::TilesetView::~TilesetView (this=0x4d72d00, __in_chrg=<optimised out>) at tilesetview.h:37
#27 0x00000000005e592a in Tiled::Internal::TilesetDock::setMapDocument (this=0xc64400, mapDocument=0x6288a20) at tilesetdock.cpp:334
#28 0x0000000000566473 in Tiled::Internal::MainWindow::mapDocumentChanged (this=0x7fffffffdbd0, mapDocument=0x6288a20) at mainwindow.cpp:1790
#29 0x0000000000615dab in Tiled::Internal::MainWindow::qt_static_metacall (_o=0x7fffffffdbd0, _c=QMetaObject::InvokeMetaMethod, _id=46, _a=0x7fffffffc740) at moc_mainwindow.cpp:317
#30 0x00007ffff666e2a6 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#31 0x0000000000613c27 in Tiled::Internal::DocumentManager::currentDocumentChanged (this=0xc572a0, _t1=0x6288a20) at moc_documentmanager.cpp:229
#32 0x000000000053653a in Tiled::Internal::DocumentManager::currentIndexChanged (this=0xc572a0) at documentmanager.cpp:417
#33 0x00000000006138e3 in Tiled::Internal::DocumentManager::qt_static_metacall (_o=0xc572a0, _c=QMetaObject::InvokeMetaMethod, _id=7, _a=0x7fffffffc940) at moc_documentmanager.cpp:148
#34 0x00007ffff666e2a6 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#35 0x00007ffff73a8dbe in QTabWidget::currentChanged(int) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#36 0x00007ffff73aae6f in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#37 0x00007ffff666e2a6 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#38 0x00007ffff739b6ae in QTabBar::currentChanged(int) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#39 0x00007ffff73a0d98 in QTabBar::setCurrentIndex(int) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#40 0x00007ffff73a335e in QTabBar::mousePressEvent(QMouseEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#41 0x00007ffff7247c12 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#42 0x00007ffff73a6a9b in QTabBar::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#43 0x00007ffff720cc8c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#44 0x00007ffff7212b61 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#45 0x00007ffff6646c2d in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#46 0x00007ffff72109e1 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#47 0x00007ffff7264bbf in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#48 0x00007ffff72669bb in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#49 0x00007ffff720cc8c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#50 0x00007ffff7211e56 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#51 0x00007ffff6646c2d in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#52 0x00007ffff6b6625c in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#53 0x00007ffff6b67925 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#54 0x00007ffff6b50858 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#55 0x00007fffed8715b0 in ?? () from /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so
#56 0x00007ffff4b78e04 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#57 0x00007ffff4b79048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#58 0x00007ffff4b790ec in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#59 0x00007ffff669398c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#60 0x00007ffff664596b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#61 0x00007ffff664c0e1 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
---Type <return> to continue, or q <return> to quit---
#62 0x00000000005581a7 in main (argc=1, argv=0x7fffffffde38) at main.cpp:300
```

**Comment by bjorn** [comment]
Thanks, that really helps! It's happening while the tileset views are being deleted, so it only happens when you have more than one tileset. Now I am able to reproduce the problem and will investigate how I can fix it once I have some time.
