### ISSUE TITLE
Have updated release builds for Ubuntu on Launchpad

### ISSUE THREAD

**Issue by bjorn** [bjorn/tiled#1270]
The daily builds at https://launchpad.net/~mapeditor.org/+archive/ubuntu/tiled are generally working nicely, but there are no release builds available for those who want something more stable.

The releases should be published to this PPA as well, and the process should be documented so that it is easy to do for each release.

**Comment by theshadowx** [comment]
Have you tried snappy? it's the new way for packaging and it gives a simple way to update.

**Comment by theshadowx** [comment]
From what I saw for other apps, they have two repos one for stable releases and the other for daily-builds.

**Comment by bjorn** [comment]
> Have you tried snap? it's the new way for packaging and it gives a simple way to update.

I've toyed around with the command-line tools but they started crashing a lot and I couldn't immediately find a lot of useful documentation yet. In addition, they had a Qt/QML based example but it got removed because it didn't work. So if even they can't get that to work then I'm not feeling very confident to try packaging a Qt based app myself right now. Eventually though, this definitely looks interesting.

> From what I saw for other apps, they have two repos one for stable releases and the other for daily-builds.

There is no need. The snapshots are installed with `apt-get install tiled-daily` and the releases will be simply called `tiled`, so they can live in the same repository.

**Comment by probonopd** [comment]
Maybe [AppImage](http://appimage.org/) might be useful for you: Package once and run on many different Linux distributions, without the need for installation. There are already several Qt-based applications out there which are distributed this way, e.g., Krita, Subsurface, and Scribus.

**Comment by bjorn** [comment]
@probonopd Hmm, I could definitely try to find some time for this, though this issue is really about having the PPA function like it should to provide more up-to-date system-installed packages.

Since recently I have Linux binary packages that seem to be working quite well (#1271), but maybe AppImage would work even better. Would need to check if they work with the itch.io app, though.

**Comment by Ablu** [comment]
I can look into this after my exams probably (in about a month) in case 
nobody else does it until then.

Regards,
Ablu

**Comment by bjorn** [comment]
If we'd ever want to provide builds from Launchpad again, we'd probably need to resolve this Launchpad import error first:
```
2021-08-10 08:21:07 INFO    Starting job.
2021-08-10 08:21:07 INFO    Getting existing bzr branch from central store.
2021-08-10 08:21:08 INFO    [chan bzr SocketAsChannelAdapter] Opened sftp connection (server version 3)
2021-08-10 08:21:08 INFO    35 bytes transferred
2021-08-10 08:21:11 INFO    [chan bzr SocketAsChannelAdapter] Opened sftp connection (server version 3)
2021-08-10 08:21:12 INFO    Importing branch.
2021-08-10 08:21:13 INFO    
Traceback (most recent call last):
  File "/srv/lp-codeimport/payloads/0f80d22c76a72f9e9eb763eb46f19ce67bb48415/scripts/code-import-worker.py", line 112, in <module>
    sys.exit(script.main())
  File "/srv/lp-codeimport/payloads/0f80d22c76a72f9e9eb763eb46f19ce67bb48415/scripts/code-import-worker.py", line 107, in main
    return import_worker.run()
  File "/srv/lp-codeimport/payloads/0f80d22c76a72f9e9eb763eb46f19ce67bb48415/lib/lp/codehosting/codeimport/worker.py", line 576, in run
    return self._doImport()
  File "/srv/lp-codeimport/payloads/0f80d22c76a72f9e9eb763eb46f19ce67bb48415/lib/lp/codehosting/codeimport/worker.py", line 780, in _doImport
    inter_branch.fetch(limit=revision_limit)
  File "/srv/lp-codeimport/payloads/0f80d22c76a72f9e9eb763eb46f19ce67bb48415/bzrplugins/git/branch.py", line 722, in fetch
    self.fetch_objects(stop_revision, fetch_tags=fetch_tags, limit=limit)
  File "/srv/lp-codeimport/payloads/0f80d22c76a72f9e9eb763eb46f19ce67bb48415/bzrplugins/git/branch.py", line 745, in fetch_objects
    determine_wants, self.source.mapping, limit=limit)
  File "/srv/lp-codeimport/payloads/0f80d22c76a72f9e9eb763eb46f19ce67bb48415/bzrplugins/git/fetch.py", line 715, in fetch_objects
    progress=lambda text: report_git_progress(pb, text))
  File "/srv/lp-codeimport/payloads/0f80d22c76a72f9e9eb763eb46f19ce67bb48415/bzrplugins/git/remote.py", line 461, in fetch_objects
    lambda x: os.write(fd, x), progress)
  File "/srv/lp-codeimport/payloads/0f80d22c76a72f9e9eb763eb46f19ce67bb48415/bzrplugins/git/remote.py", line 451, in fetch_pack
    pack_data, progress)
  File "/srv/lp-codeimport/payloads/0f80d22c76a72f9e9eb763eb46f19ce67bb48415/bzrplugins/git/remote.py", line 270, in fetch_pack
    graph_walker, pack_data, progress)
  File "/srv/lp-codeimport/payloads/0f80d22c76a72f9e9eb763eb46f19ce67bb48415/env/local/lib/python2.7/site-packages/dulwich/client.py", line 749, in fetch_pack
    proto, negotiated_capabilities, graph_walker, wants, can_read)
  File "/srv/lp-codeimport/payloads/0f80d22c76a72f9e9eb763eb46f19ce67bb48415/env/local/lib/python2.7/site-packages/dulwich/client.py", line 574, in _handle_upload_pack_head
    have = next(graph_walker)
  File "/srv/lp-codeimport/payloads/0f80d22c76a72f9e9eb763eb46f19ce67bb48415/env/local/lib/python2.7/site-packages/dulwich/object_store.py", line 1173, in next
    ps = self.get_parents(ret)
  File "/srv/lp-codeimport/payloads/0f80d22c76a72f9e9eb763eb46f19ce67bb48415/bzrplugins/git/fetch.py", line 708, in <lambda>
    lambda sha: store[sha].parents)
  File "/srv/lp-codeimport/payloads/0f80d22c76a72f9e9eb763eb46f19ce67bb48415/bzrplugins/git/object_store.py", line 674, in __getitem__
    _check_expected_sha(sha, commit)
  File "/srv/lp-codeimport/payloads/0f80d22c76a72f9e9eb763eb46f19ce67bb48415/bzrplugins/git/object_store.py", line 155, in _check_expected_sha
    expected_sha))
AssertionError: Invalid sha for <Commit 522299f9384b449139fc0e96dbf951e86dcee24a>: 91a3bf698e8040985d2ffc2822ef0f176ecd5ed2
Import failed:
Traceback (most recent call last):
Failure: twisted.internet.error.ProcessTerminated: A process has ended with a probable error condition: process ended with exit code 1.
```
This error is preventing [`lp:tiled`](https://code.launchpad.net/~mapeditor.org/tiled/master) from being updated, which is what the [tiled-daily](https://code.launchpad.net/~mapeditor.org/+recipe/tiled-daily) recipe is based on.

Alternatively, we'd build the .deb elsewhere and [upload them](https://help.launchpad.net/Packaging/PPA/Uploading) to the PPA.

Of course, in the meantime we already provide an AppImage and a snap package, both of which can be used on Ubuntu.

**Comment by bjorn** [comment]
Going to close this since I don't think getting the PPA to work is worth it given that the snap is readily available on Ubuntu, as well as the Flatpak and the AppImage with some effort.
