### ISSUE TITLE
IndexOutOfBoundsException when loading tmx maps

### ISSUE THREAD

**Issue by Shorttail** [bjorn/tiled#1626]
Inside the test resources for libtiled-java, create a new folder named "other" and copy desert.tmx and desert.tsx into it. Add the following test case:

```java
@Test
public void testErrorReadingMap() throws Exception {
    new TMXMapReader().readMap("other/desert.tmx");
}
```

The test should fail with an IndexOutOfBoundsException similar to this:

```
java.lang.IndexOutOfBoundsException: Index: 16, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at tiled.core.TileSet.getTile(TileSet.java:419)
	at tiled.io.TMXMapReader.getTileForTileGID(TMXMapReader.java:727)
	at tiled.io.TMXMapReader.setTileAtFromTileId(TMXMapReader.java:713)
	at tiled.io.TMXMapReader.readLayer(TMXMapReader.java:626)
	at tiled.io.TMXMapReader.buildMap(TMXMapReader.java:812)
	at tiled.io.TMXMapReader.unmarshal(TMXMapReader.java:846)
	at tiled.io.TMXMapReader.readMap(TMXMapReader.java:873)
```

When the tmx and tsx files are in their original position, which is the same as the package for TMXMapReader, this exception is now thrown.

**Comment by bjorn** [comment]
Thanks @Shorttail!

Actually after looking into the issue for a while, it occurred to me that you mention only copying the `desert.tmx` and `desert.tsx` files. However, the `desert.tsx` file refers to `tmw_desert_spacing.png`. If that image file isn't present the map won't load. However, it isn't expected to throw the above exception in that case, it should exit as follows:
```
Error while reading the map:
Can't read input file!
```
At least, `TMXViewer` does. When I do also copy the image file, things seem to work fine.

That `getTileForTileGID` is catching the wrong exception though. It's trying to catch `ArrayIndexOutOfBoundsException` but the exception raised is `IndexOutOfBoundsException`, since `tilesets` was changed from a `Vector` to an `ArrayList`. However, it shouldn't run into either exception in this case.

**Comment by Shorttail** [comment]
Good catch. I copied tmx_desert_spacing.png as well, and now it fails with this error instead:

```
java.io.FileNotFoundException: some\path\tiled\util\java\libtiled-java\other\desert.tmx (The system cannot find the path specified)
	at org.mapeditor.io.MapReaderTest.testErrorReadingMap(MapReaderTest.java:50)
```

Now it is looking for the files in the root folder when running mvn test.

**Comment by bjorn** [comment]
Maybe there is something special when running tests. I just tried by running TMXViewer from IntelliJ. Hopefully @mikepthomas knows more.

**Comment by Shorttail** [comment]
I'm getting the same error when running the test in Eclipse:

```
java.io.FileNotFoundException: some\path\other\desert.tmx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at java.net.URL.openStream(URL.java:1045)
	at tiled.io.TMXMapReader.readMap(TMXMapReader.java:866)
	at tiled.io.MapReaderTest.testErrorReadingMap(MapReaderTest.java:50)
```

I recall a similar problem with the older reflection based code. I've had a ton of trouble loading files with anything that has to do with URLs and getResourceAsStream when mixing Gradle, Eclipse, and manually running programs. In my project all non-test resources are placed in a single folder found at ../external, which is reachable the exact same way for every subproject. Resources for tests are placed in their base folder without a package structure.

In Eclipse and Maven I can make it work by adding the other folder to the base of the project instead of in the resources folder.

**Comment by mikepthomas** [comment]
All the other tests seem to be using the getFileFromResources method... if I change the test to the following it works:
```
@Test
public void testErrorReadingMap() throws Exception {
    File mapFile = getFileFromResources("other/desert.tmx");
    new TMXMapReader().readMap(mapFile.getAbsolutePath());
}
```
![image](https://user-images.githubusercontent.com/13928052/27552388-1cd4cd2c-5a9f-11e7-8cd2-d0bfc66a74d3.png)

**Comment by Shorttail** [comment]
Thanks for the help. I consider the problem solved.
